languageCode = "en"
languageName = "English"
weight = 1
title = "Abhinav Malik"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2006"
  description = "Senior Engineering Manager · Streaming Apps | Android, iOS & Roku | TiVo"