[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Streaming"
  pageRef = "tags/streaming"
  weight = 30

[[main]]
  name = "Ad Tech"
  pageRef = "tags/ad-tech"
  weight = 40

[[main]]
  name = "Leadership"
  pageRef = "tags/leadership"
  weight = 50