[[main]]
  name = "Resume"
  pageRef = "resume"
  weight = 10

[[main]]
  name = "About Me"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Leadership"
  pageRef = "tags/leadership"
  weight = 30

[[main]]
  name = "Tech"
  pageRef = "tags/tech"
  weight = 40