[[main]]
  name = "Resume"
  url = "/resume/"
  weight = 10

[[main]]
  name = "About Me"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Leadership"
  url = "/tags/leadership/"
  weight = 30

[[main]]
  name = "Tech"
  url = "/tags/tech/"
  weight = 40