# -- Site Configuration --
# Congo theme docs: https://jpanther.github.io/congo/docs/configuration/

colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

robots = ""

[header]
  layout = "fixed"

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = false

[article]
  showDate = true
  showAuthor = true
  showHero = false
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showSummary = true
  sharingLinks = ["linkedin", "twitter"]

[list]
  showBreadcrumbs = false
  showSummary = true
  groupByYear = true
  cardView = true

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = false

[term]
  showHero = false
  showTableOfContents = false
  cardView = true
